#!/usr/bin/env python3

HELP = """
This script verifies that all platform-specific dependencies are available and
configured properly so that the project can be built with `cargo`.

The `-y` or `-n` flags can be provided to auto-accept or auto-deny any prompts
for user confirmation.

The `--no-cache` flag makes the script delete any cached build script data
before executing.

The `--no-cargo-clean` flag makes the script skip running `cargo clean`
(advanced users only).
""".rstrip()

from functools import cache
import json
import os
import re
import sys
import tempfile
import time
import typing
from dataclasses import dataclass
from typing import Any, Iterable, Literal, Union, Optional

import build_util.log as log
import build_util.sh as sh
import build_util.user as user
import build_util.ffmpeg_build as ffmpeg_build


@dataclass
class Args:
    no_cache: bool
    no_cargo_clean: bool


def parse_args() -> Args:
    """
    Parses command line arguments. Returns whether or not `--no-cache` was
    provided.
    """

    ARG_0 = sys.argv[0]
    USAGE = f"""
Usage:
    {ARG_0} [-y|-n] [--no-cache] [--no-cargo-clean]
    {ARG_0} --help
""".rstrip()

    auto_confirm = None
    no_cache = False
    no_cargo_clean = False

    for arg in sys.argv[1:]:
        if arg in ("-h", "--help", "help", "/h", "/?", "h", "?"):
            print(f"{USAGE}{HELP}")
            sys.exit(int(len(sys.argv) != 2))

        if arg in ("-y", "-n"):
            if auto_confirm:
                if arg[1] == auto_confirm:
                    log.fatal(f"Repeat argument `{arg}`." + USAGE)
                else:
                    log.fatal(
                        f"Arguments `{arg}` and `-{auto_confirm}`"
                        + " are incompatible."
                        + USAGE
                    )
            auto_confirm = arg[1]
            user.set_confirm_auto_answer(auto_confirm)

        elif arg == "--no-cache":
            if no_cache:
                log.fatal(f"Repeat argument `{arg}`." + USAGE)
            no_cache = True

        elif arg == "--no-cargo-clean":
            if no_cargo_clean:
                log.fatal(f"Repeat argument `{arg}`." + USAGE)
            no_cargo_clean = True

        else:
            log.fatal(f"Unknown argument `{arg}`." + USAGE)

    return Args(no_cache, no_cargo_clean)


def create_cargo_config_for_env(
    env: Optional[dict[str, str]] = None,
    extra_pkgconfig_dirs: Optional[list[str]] = None,
) -> None:
    """
    Create a `.cargo/config.toml` file that sets the environment variables from
    `env`.

    `FFMPEG_DIR` always gets set to point to FFmpeg's build folder.

    `PKG_CONFIG_LIBDIR` always gets set to point to FFmpeg's `pkgconfig` folder.
    You can add additional paths to `PKG_CONFIG_LIBDIR` by providing
    `extra_pkgconfig_dirs`.
    """

    env = env or {}
    env["FFMPEG_DIR"] = ffmpeg_build.path(absolute=True)
    env["PKG_CONFIG_LIBDIR"] = ":".join(
        [ffmpeg_build.pkgconfig(absolute=True)] + (extra_pkgconfig_dirs or [])
    )

    path = f".cargo{os.sep}config.toml"

    if os.path.exists(path) and not user.confirm(
        f"A `{path}` file already exists. Overwrite?"
    ):
        log.fatal(f"Failed to create `{path}`.")
    else:
        os.makedirs(".cargo", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# Generated by `build_setup.py`.\n"
            + "[env]\n"
            + "\n".join(
                f"{key} = \"{value.encode('unicode_escape').decode('ascii')}\""
                for key, value in env.items()
            )
            + "\n"
        )

    log.info(f"Cargo config generated (`{path}`).")


def windows() -> None:
    """
    Handles build setup for Windows builds.
    """

    from build_util.platforms import win

    vs_installer_dir = win.vs_installer_dir()
    vs_installation_dir = win.vs_installation_dir()

    # Collect a list of all Visual Studio components that are installed.
    def get_installed_vs_components() -> list[str]:
        log.info("Exporting installed Visual Studio components...")

        # We'll use `vs_installer` to query installed components. The result
        # will be written to a JSON config file we can read.

        temp_vs_installer_config_path = (
            f"{tempfile.gettempdir()}\\config.vsconfig"
        )

        vs_installer_err_msg = (
            "Failed to export installed Visual Studio components."
            + " Make sure the Visual Studio Installer isn't already runnning."
        )

        try:
            sh.run_cmd(
                f"{vs_installer_dir}\\vs_installer.exe",
                "--installPath",
                vs_installation_dir,
                "export",
                "--config",
                temp_vs_installer_config_path,
                "--quiet",
                "--noUpdateInstaller",
                non_fatal=True,
            )
        except sh.CmdException as e:
            log.fatal(f"{e}\n{vs_installer_err_msg}")

        try:
            with open(temp_vs_installer_config_path) as f:
                installed_components = json.load(f)["components"]
            os.remove(temp_vs_installer_config_path)
        except FileNotFoundError:
            log.fatal(vs_installer_err_msg)

        log.info("Installed Visual Studio components exported.")
        return installed_components

    installed_vs_components = get_installed_vs_components()

    # Ensures we have a required Visual Studio component installed.
    def ensure_vs_component_is_installed(
        component_name: str, component_regex: str
    ) -> None:
        component_is_installed = any(
            re.fullmatch(component_regex, installed_component) is not None
            for installed_component in installed_vs_components
        )

        if not component_is_installed:
            sh.start_cmd(f"{vs_installer_dir}\\vs_installer.exe")
            log.fatal(
                f"Missing the `{component_name}` component."
                + " Please use the Visual Studio Installer to install it.\n"
                + "Trying to opening the Visual Studio Installer..."
            )

        log.info(
            f"The `{component_name}` Visual Studio component is installed."
        )

    # At a minimum, rust needs C++ build tools and a Windows 11 SDK.
    ensure_vs_component_is_installed(
        "C++ x64/x86 build tools (Latest)",
        r"Microsoft\.VisualStudio\.Component\.VC\.Tools\..*",
    )
    ensure_vs_component_is_installed(
        "Windows 11 SDK",
        r"Microsoft\.VisualStudio\.Component\.Windows11SDK\..*",
    )

    # `ffmpeg-next` uses `bindgen` which requires `libclang` to generate rust
    # bindings. We get that from this component.
    ensure_vs_component_is_installed(
        "C++ Clang Compiler for Windows",
        r"Microsoft\.VisualStudio\.Component\.VC\.Llvm\.Clang",
    )

    # Finds the `libclang` DLL.
    def get_libclang_path() -> str:
        # `libclang` needs to be installed for FFmpeg-next to be able to create
        # rust bindings.
        libclang_path = f"{vs_installation_dir}\\VC\\Tools\\LLVM\\x64\\bin"
        sh.ensure_path_exists(f"{libclang_path}\\libclang.dll", kind="file")
        log.info("Found `libclang`.")

        return libclang_path

    # Try and ensure we're using the right header files for generating rust
    # bindings for FFmpeg.
    def try_to_get_clang_include_dir() -> Optional[str]:
        try:
            clang_dir = (
                f"{vs_installation_dir}\\VC\\Tools\\LLVM\\x64\\lib\\clang"
            )

            newest_clang_version = sorted(
                version
                for version in os.listdir(clang_dir)
                if os.path.isdir(os.path.join(clang_dir, version))
            )[-1]

            clang_include_dir = f"{clang_dir}\\{newest_clang_version}\\include"
            sh.ensure_path_exists(clang_include_dir, kind="dir", non_fatal=True)

            log.info("Found Clang include directory.")
        except (FileNotFoundError, IndexError, sh.DoesntExistException):
            log.warning(
                "Failed to find Clang include directory. Compilation may fail."
            )
            clang_include_dir = None

        return clang_include_dir

    libclang_path = get_libclang_path()
    clang_include_dir = try_to_get_clang_include_dir()

    # See: https://github.com/zmwangx/rust-ffmpeg/wiki/Notes-on-building

    # We need to set `LIBCLANG_PATH` so that `ffmpeg-next` can make bindings.
    env = {"LIBCLANG_PATH": libclang_path}
    if clang_include_dir is not None:
        # If we found Clang's include directory we'll explicitly pass it to
        # `bindgen` (the library `ffmpeg-next` uses to generate rust bindings)
        # so that it doesn't get confused and try to build using mingw headers
        # or something else weird.
        env["BINDGEN_EXTRA_CLANG_ARGS"] = f"-I{clang_include_dir}"

    create_cargo_config_for_env(env)


def mac_os() -> None:
    """
    Handles build setup for macOS builds.
    """

    # If the user doesn't have `clang` there's a good chance they need to run
    # `xcode-select --install`. This is technically optional.
    try:
        sh.ensure_cmd_exists("clang", non_fatal=True)
    except:
        if user.confirm(
            "`clang` could not be found. You may need to install Xcode's "
            + "Command Line Tools. Install now?"
        ):
            log.info(
                "Installing Xcode's Command Line Tools. "
                + "This may take a while..."
            )
            sh.run_cmd("xcode-select", "--install")
        else:
            log.warning(
                "Continuing without finding `clang`. The build may fail."
            )
    else:
        log.info("Found `clang`.")

    def check_for_brew() -> bool:
        try:
            sh.ensure_cmd_exists("brew", non_fatal=True)
        except sh.DoesntExistException:
            if not user.confirm(
                "Building on macOS requires `pkg-config`, usually installed "
                + "through the Homebrew package manager. You do not have "
                + "Homebrew installed. Start Homebrew install? (you'll need "
                + "to be a system admin)"
            ):
                log.info("Continuing without checking for `pkg-config`...")
                return False

            # This comes from the download instructions here: https://brew.sh/
            sh.run_cmd(
                '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"',
                shell=True,
            )
            sh.ensure_cmd_exists("brew")

        log.info("Found Homebrew package manager.")
        return True

    last_installed_pkgs: Optional[list[dict[str, Any]]] = None

    def is_installed_with_brew(
        pkg_name: str, ask_to_install: bool = False
    ) -> bool:
        nonlocal last_installed_pkgs
        if last_installed_pkgs is None:
            last_installed_pkgs = typing.cast(
                list[dict[str, Any]],
                json.loads(
                    sh.run_cmd(
                        "brew",
                        "info",
                        "--installed",
                        "--json",
                        show_output=False,
                    )
                ),
            )
        installed_pkgs = last_installed_pkgs

        def names_from_pkg_dict(pkg_dict: dict[str, Any]) -> list[str]:
            ret: list[str] = []
            for key in ("name", "full_name", "oldnames", "aliases"):
                val = pkg_dict.get(key)
                if isinstance(val, str):
                    ret.append(val)
                elif isinstance(val, list):
                    ret.extend(
                        sub_val
                        for sub_val in typing.cast(list[Union[str, Any]], val)
                        if isinstance(sub_val, str)
                    )
            return ret

        is_already_installed = any(
            pkg_name in names_from_pkg_dict(pkg_dict)
            for pkg_dict in installed_pkgs
        )

        if is_already_installed or not ask_to_install:
            return is_already_installed

        if not user.confirm(
            f"It doesn't look like you have `{pkg_name}` installed."
            + " Install with Homebrew?"
        ):
            log.info(f"Continuing without installing `{pkg_name}`...")
            return False

        log.info(
            f"Installing `{pkg_name}` with Homebrew."
            + " This can take a very long time."
        )
        last_installed_pkgs = None

        try:
            sh.run_cmd("brew", "install", pkg_name, non_fatal=True)

        # Sometimes Homebrew likes to return an error exit code even when it
        # installs correctly. If that happens we'll just log it and move on with
        # our lives.
        except sh.CmdException as e:
            if not is_installed_with_brew(pkg_name):  # recursion!
                log.fatal(f"{e}")
            log.warning(f"{e} `{pkg_name}` seems to have installed regardless.")

        return True

    # The user needs `pkg-config`, we'll let them install through Homebrew if
    # they don't have it. This is technically optional.
    try:
        sh.ensure_cmd_exists("pkg-config", non_fatal=True)
    except sh.DoesntExistException:
        log.info("Couldn't find `pkg-config`. Checking with Homebrew...")
        if check_for_brew() and is_installed_with_brew(
            "pkg-config", ask_to_install=True
        ):
            log.info("Found `pkg-config` with Homebrew.")
        else:
            log.warning(
                "Continuing without finding `pkg-config`. The build may fail."
            )
    else:
        log.info("Found `pkg-config`.")

    create_cargo_config_for_env()


def linux() -> None:
    """
    Handles build setup for Linux builds.
    """

    @cache
    def get_package_manager() -> str:
        log.info("Looking for package manager...")
        for pkg_manager in ["apt-get", "dnf", "yum", "pacman", "apk", "zypper"]:
            try:
                sh.ensure_cmd_exists(pkg_manager, non_fatal=True)
            except sh.DoesntExistException:
                continue
            log.info(f"Found package manager `{pkg_manager}`.")
            return pkg_manager
        log.fatal(
            "No known package manager to install packages with. "
            + "Please install manually."
        )

    def should_install_cmd(cmd: str, required: bool = False) -> bool:
        try:
            sh.ensure_cmd_exists(cmd, non_fatal=True)
        except sh.DoesntExistException:
            install_cmd = user.confirm(
                f"Couldn't find `{cmd}`. Would you like to try installing it?"
            )
            if not install_cmd:
                if required:
                    log.fatal(f"`{cmd}` is required to continue.")
                log.warning(
                    f"Continuing without finding `{cmd}`. The build may fail."
                )
            return install_cmd
        log.info(f"Found `{cmd}`.")
        return False  # found

    def package_manager_install(pkg: str) -> None:
        PKG_NAMES = {
            "clang": {
                "apt-get": "clang",
                "dnf": "clang",
                "yum": "clang",
                "pacman": "clang",
                "apk": "clang",
                "zypper": "clang",
            },
            "pkg-config": {
                "apt-get": "pkg-config",
                "dnf": "pkgconf-pkg-config",
                "yum": "pkgconf-pkg-config",
                "pacman": "pkgconf",
                "apk": "pkgconf",
                "zypper": "pkg-config",
            },
            "alsa-dev": {
                "apt-get": "libasound2-dev",
                "dnf": "alsa-lib-devel",
                "yum": "alsa-lib-devel",
                "pacman": "alsa-lib",
                "apk": "alsa-lib-dev",
                "zypper": "alsa-devel",
            },
        }

        package_manager = get_package_manager()
        pkg_name = PKG_NAMES[pkg][package_manager]

        env = {}
        if package_manager == "apt-get":
            install_cmd = ["apt-get", "install", "-y"]
            env["DEBIAN_FRONTEND"] = "noninteractive"
        elif package_manager in ("dnf", "yum"):
            install_cmd = [package_manager, "install", "-y"]
        elif package_manager == "pacman":
            install_cmd = ["pacman", "-S", "--noconfirm"]
        elif package_manager == "apk":
            install_cmd = ["apk", "add"]
        elif package_manager == "zypper":
            install_cmd = ["zypper", "--non-interactive", "install"]

        # `sudo` if not running as root.
        if os.geteuid() != 0:
            install_cmd.insert(0, "sudo")

        sh.run_cmd(*install_cmd, pkg_name, env_overrides=env)

    if should_install_cmd("clang"):
        package_manager_install("clang")

    if should_install_cmd("pkg-config", required=True):
        package_manager_install("pkg-config")
    sh.ensure_cmd_exists("pkg-config")

    # We need ALSA dev headers for `midir` and we need to tell `pkg-config`
    # where they are.
    try:
        sh.run_cmd(
            *("pkg-config", "--exists", "alsa"),
            non_fatal=True,
            show_output=False,
        )
    except:
        if user.confirm(
            f"Couldn't find ALSA development headers. "
            + "Would you like to try installing them?"
        ):
            package_manager_install("alsa-dev")
        else:
            log.fatal(f"ALSA development headers are required to continue.")
    alsa_dev_headers = sh.run_cmd(
        *("pkg-config", "--variable=pcfiledir", "alsa"),
        show_output=False,
    )

    create_cargo_config_for_env(extra_pkgconfig_dirs=[alsa_dev_headers])


def main() -> None:
    start_time = time.time()

    args = parse_args()

    sh.require_script_in_working_dir()

    if args.no_cache and sh.rm_path(
        sh.cache_dir(create=False), allow_missing=True
    ):
        log.info("Build script cache cleared (`--no-cache` provided).")

    ffmpeg_build.get_ffmpeg()
    sh.ensure_cmd_exists("cargo")

    if sh.build_os() == "windows":
        windows()
    elif sh.build_os() == "darwin":  # macOS
        mac_os()
    elif sh.build_os() == "linux":
        linux()

    if args.no_cargo_clean:
        log.warning(
            "The build directory has not been cleaned "
            + "(`--no-cargo-clean` provided)."
        )
    else:
        sh.run_cmd("cargo", "clean")
        log.info("Build directory cleaned.")

    elapsed_time = time.time() - start_time
    log.success(f"Build setup completed in {log.fmt_time(elapsed_time)}.")


if __name__ == "__main__":
    sh.catch_stop_signal(main)
