[package]
name = "tauri-editor"
version = "0.1.0"
edition = "2021"

[lib]
name = "tauri_editor_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { workspace = true }
serde_json = { workspace = true }
engine = { workspace = true }
media = { workspace = true }
util = { workspace = true, features = ["local_data"] }
wgpu = { version = "27", default-features = false, features = [
    "vulkan",
    "metal",
    "wgsl",
] }
pollster = "0.4"
